services:
  postgres:
    image: supabase/postgres:15.1.0.103
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
#    command:
#      - "postgres"
#      - "-c"
#      - "wal_level=logical"
#      - "-c"
#      - "max_replication_slots=10"
#      - "-c"
#      - "max_wal_senders=10"
    ports:
      - "5432:5432"
